name: Main Workflow
 
on:
  workflow_call:
    inputs:
      rocm_release:
        type: string
        description: ROCm release version
        required: true
      performance_reports_repo:
        type: string
        description: Result repository
        required: true
      benchmark_utils_repo:
        type: string
        description: Repository where benchmark utils are stored
        required: true
      organization:
        type: string
        description: Organization based on which location of files will be different
        required: true
 
jobs:
  main_job:
    runs-on: ubuntu-latest
    steps:
      - name: check inputs
        run: |
         echo "ROCM: ${{ inputs.rocm_release }}"
         echo "ORG: ${{ inputs.organization }}"
         echo "REPORTS: ${{ inputs.performance_reports_repo }}"
         echo "UTILS: ${{ inputs.benchmark_utils_repo }}"
